#!/bin/sh

choices="Speakers\nHeadset"

chosen=$(echo -e "$choices" | dmenu -i -p "Select Audio Source")

case "$chosen" in
  Speakers) pactl set-default-sink alsa_output.pci-0000_00_1f.3.analog-stereo ;;
  Headset) pactl set-default-sink alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.stereo-game ;;
esac


# MADE BY MYSELF BUT HEAVILY INSPIRED BY LUKE SMITH
